### PR TITLE
issue #14 link added to Contribute item

### PR DESCRIPTION
**Pull request by Sky-De**
hi there 
i added just link to contribute item in this commit 
also in second commit which i will pull , i fix this problem and a little bit more clear and reusable code

### CODE REVIEW

**Comment by Dhruv-Sood** [comment]
Clicking on home is causing the page to reload. Can you fix it?

**Comment by Sky-De** [comment]
@Dhruv-Sood it is done, now links will not cause refresh anymore
also i added nav to app component to serve to entire application
it is DONE

**Comment by Dhruv-Sood** [comment]
Looks good, can you also remove the navbar from timerpage?

**Comment by Dhruv-Sood** [comment]
Also on smaller devices it is still reloading

**Comment by Sky-De** [comment]
sure 
it is done

1.duplicate nav removed
2.refresh problem on small devices fixed

**NOTE** : your app dose not follow scable and clean code structure , i highly recommend you if you want keep developing your app , follow good practice approaches,
if you got any question feel free to ask otherwise merge laset commit 
thanks

**Comment by Dhruv-Sood** [comment]
Awesome!!
Thanks for contributing @Sky-De 
Mind giving this project a 🌟?

**Pull request merged**
